version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 417623538526.dkr.ecr.us-east-1.amazonaws.com/python_webapp
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t python_webapp .
      - docker tag python_webapp:latest 417623538526.dkr.ecr.us-east-1.amazonaws.com/python_webapp:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 417623538526.dkr.ecr.us-east-1.amazonaws.com/python_webapp:latest
artifacts:
  files:
    - k8s/deployment.yaml
